// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChgpzHD2NFoJKut9QCIDR6eRK4Nle52zY',
    appId: '1:404774671115:web:9d776139e98eb0f8ed480e',
    messagingSenderId: '404774671115',
    projectId: 'ev-project-8b58e',
    authDomain: 'ev-project-8b58e.firebaseapp.com',
    storageBucket: 'ev-project-8b58e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTghaZq7nxb5W1X02ICfqw41O_MHr7c8',
    appId: '1:404774671115:android:919445b9a990b079ed480e',
    messagingSenderId: '404774671115',
    projectId: 'ev-project-8b58e',
    storageBucket: 'ev-project-8b58e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD13UZ6STnu3PzBHLs7igRWtPMBVGtzss',
    appId: '1:404774671115:ios:7b40d99f3fa1ffa4ed480e',
    messagingSenderId: '404774671115',
    projectId: 'ev-project-8b58e',
    storageBucket: 'ev-project-8b58e.appspot.com',
    iosClientId: '404774671115-evjk2g1gmt2n11c14ju8jn0dnq6l3vss.apps.googleusercontent.com',
    iosBundleId: 'com.example.evCharger',
  );
}
